import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import localFont from "next/font/local";

const caveat = localFont({
  src: "../public/fonts/Caveat-VariableFont_wght.ttf",
  variable: "--font-caveat",
  display: "swap",
});

const intro = localFont({
  src: "../public/fonts/Intro-Regular-Alt.woff2",
  variable: "--font-intro",
  display: "swap",
});


const jura = localFont({
  src: "../public/fonts/Jura-VariableFont_wght.ttf",
  variable: "--font-jura",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body
        className={`
          ${caveat.variable}
          ${intro.variable}
          ${jura.variable}
          antialiased
          `}
        >
        {children}
      </body>
    </html>
  );
}
